# Database
spring.datasource.url=jdbc:postgresql://localhost:6541/shareit
spring.datasource.username=shareit
spring.datasource.password=shareit

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.sql.init.mode=always

# Server
server.port=9090

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=trace
logging.level.org.springframework.orm.jpa=INFO
logging.level.org.springframework.transaction=INFO
logging.level.org.springframework.transaction.interceptor=TRACE
logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG
logging.level.ru.practicum.shareit=INFO

app.booking.time-tolerance-seconds=5