# Server
server.port=8080
# Application logging
logging.level.ru.practicum.shareit=INFO

# Spring Web (???????????)
logging.level.org.springframework.web=DEBUG

# Validation (???????????)
spring.mvc.validate-on-parse=true

shareit-server.url=http://localhost:9090